start:
  description: Start mowing
  target:
    entity:
      domain: vacuum

pause:
  description: Pause mowing
  target:
    entity:
      domain: vacuum

home:
  description: Send device to dock
  target:
    entity:
      domain: vacuum

lock:
  description: Toggle device lock
  target:
    entity:
      domain: vacuum

restart:
  description: Restart device
  target:
    entity:
      domain: vacuum

edgecut:
  description: Start edgecut (if supported)
  target:
    entity:
      domain: vacuum

partymode:
  description: Toggle PartyMode (if supported)
  target:
    entity:
      domain: vacuum

setzone:
  description: Set which zone to be mowed next
  target:
    entity:
      domain: vacuum
  fields:
    zone:
      description: Sets the zone number, ranging from 0 to 3, to be mowed next
      example: 1
      required: true
      default: 0
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
            - "3"

config:
  description: Set device config parameters
  target:
    entity:
      domain: vacuum
  fields:
    raindelay:
      description: Set rain delay. Time in minutes ranging from 0 to 300. 0 = Disabled
      example: 30
    timeextension:
      description: Set time extension. Extension in % ranging from -100 to 100
      example: -23
      selector:
        number:
          min: -100
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    multizone_distances:
      description: Set multizone distances. Distances in meter. 0 = Disabled
      example: '[15, 80, 120, 155]'
    multizone_probabilities:
      description: Set multizone probabilities. Probabilities in parts-of-ten. 1 = 10%, 2 = 20%, ...
      example: '[5, 1, 2, 2]'
