name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Update manifest.json"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.version.outputs.version }} --path /custom_components/landroid_cloud/
      - name: Commit manifest update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./custom_components/landroid_cloud/manifest.json
          git commit -m "Updated manifest.json"
          git push
      - name: Create zip
        run: |
          cd custom_components/landroid_cloud
          zip landroid_cloud.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/landroid_cloud/landroid_cloud.zip
          asset_name: landroid_cloud.zip
          tag: ${{ github.ref }}
          overwrite: true